#Ifndef ACTORTYPES_BI
#Define ACTORTYPES_BI

Namespace act

Enum ActorTypes Explicit
	UNKNOWN = 0,
	DECORATIVE_LIGHT = 1,
	DECORATIVE_MODEL = 2,
	DECORATIVE_COLLIDER = 3,
	PORTAL = 4,
	GRAPHINTERFACE = 5,
	CAMERAINTERFACE = 6,
	DRAWBUFFERINTERFACE = 7
End Enum

End Namespace 

#EndIf
