#Include "staticlist.bi"
#Include "physics.bi"
#Include "actorbank.bi"

DECLARE_PRIMITIVE_PTR(BlockGrid)
DECLARE_STATICLIST(BlockGridPtr)
DEFINE_STATICLIST(BlockGridPtr)

DECLARE_PRIMITIVE_PTR(DynamicAABB)
DECLARE_STATICLIST(DynamicAABBPtr)
DEFINE_STATICLIST(DynamicAABBPtr)

DECLARE_PRIMITIVE_PTR(Actor)
DECLARE_STATICLIST(ActorPtr)
DEFINE_STATICLIST(ActorPtr)
